# permissions for end users to edit steps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: step-editor-role
rules:
- apiGroups:
  - webapp.example.com
  resources:
  - steps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.example.com
  resources:
  - steps/status
  verbs:
  - get
