# permissions for end users to view steps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: step-viewer-role
rules:
- apiGroups:
  - webapp.example.com
  resources:
  - steps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.example.com
  resources:
  - steps/status
  verbs:
  - get
