# permissions for end users to edit containersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerset-editor-role
rules:
- apiGroups:
  - workloads.infracloud.io
  resources:
  - containersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.infracloud.io
  resources:
  - containersets/status
  verbs:
  - get
